services:
  - type: web
    name: farmabol-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: PGUSER
        fromDatabase:
          name: farmabol-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: farmabol-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: farmabol-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: farmabol-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: farmabol-db
          property: database

databases:
  - name: farmabol-db
    plan: free
    databaseName: farmabol
    user: farmabol_user
